### ISSUE TITLE
Opening preference pane resolves in crash

### ISSUE THREAD

**Issue by dschreij** [smathot/QProgEdit#15]
Version 4.0.2

When I click the properties pane in OpenSesame, I see an error with the following traceback

```
Traceback (most recent call last):
  File "../smathot/QProgEdit/QProgEdit/_qtabmanager.py", line 414, in togglePrefs
    self.currentWidget().togglePrefs(visible)
  File "../smathot/QProgEdit/QProgEdit/_qprogedit.py", line 254, in togglePrefs
    self.toggle(self.prefs, visible)
  File "../smathot/QProgEdit/QProgEdit/_qprogedit.py", line 214, in toggle
    a = QtCore.QPropertyAnimation(widget, u'maximumHeight', widget)
TypeError: arguments did not match any overloaded call:
  QPropertyAnimation(parent: QObject = None): too many arguments
  QPropertyAnimation(QObject, Union[QByteArray, bytes, bytearray], parent: QObject = None): argument 2 has unexpected type 'unicode'
```
Seems to be a unicode error. Don't you love those ;)

**Comment by smathot** [comment]
I think this has to do with the version of PyQt. What version are you using?

**Comment by dschreij** [comment]
I currently use 5.6.1. It still works with Qt 4.8.7 indeed.

**Comment by smathot** [comment]
Could you patch it? I can't replicate the problem on my system. I think it should work on all versions if you pass a `QByteArray`, but better to be sure.

**Comment by dschreij** [comment]
Done, and sent you a pull request: #16
