### ISSUE TITLE
QEditor not recognized as child of QObject

### ISSUE THREAD

**Issue by dschreij** [smathot/QProgEdit#18]
After clicking on an item in the OpenSesame tree overview, the following traceback is shown:

~~~
Traceback (most recent call last):
  File "/Users/daniel/Github/OpenSesame/libqtopensesame/widgets/tree_overview.py", line 314, in mousePressEvent
    target_treeitem.open_tab()
  File "/Users/daniel/Github/OpenSesame/libqtopensesame/items/qtitem.py", line 122, in open_tab
    self.tabwidget.add(self.widget(), self.item_icon(), self.name)
  File "/Users/daniel/Github/OpenSesame/libqtopensesame/items/qtitem.py", line 46, in inner
    self.init_edit_widget()
  File "/Users/daniel/Github/OpenSesame/libqtopensesame/items/sketchpad.py", line 48, in init_edit_widget
    feedpad.init_edit_widget(self)
  File "/Users/daniel/Github/OpenSesame/libqtopensesame/items/feedpad.py", line 44, in init_edit_widget
    qtplugin.init_edit_widget(self, False)
  File "/Users/daniel/Github/OpenSesame/libqtopensesame/items/qtitem.py", line 287, in init_edit_widget
    self._script_widget.addTab(u'Script').setLang(u'OpenSesame')
  File "../smathot/QProgEdit/QProgEdit/_qtabmanager.py", line 124, in addTab
    progEdit = QProgEdit(self, title=title)
  File "../smathot/QProgEdit/QProgEdit/_qprogedit.py", line 65, in __init__
    self.editor = QEditor(self, **editorParams)
  File "../smathot/QProgEdit/QProgEdit/_qeditor.py", line 58, in __init__
    self.setLang()
  File "../smathot/QProgEdit/QProgEdit/_qeditor.py", line 455, in setLang
    colorScheme=self.cfg.qProgEditColorScheme)
  File "../smathot/QProgEdit/QProgEdit/_qlexer.py", line 213, in QLexer
    lexer = QFallbackLexer(editor)
TypeError: QsciLexer(parent: QObject = None): argument 1 has unexpected type 'QEditor'
~~~

I think we've seen this one before in the past, and then I solved it by downgrading pyqt5 or qt5 to a previous version. Since we are a couple of versions further and this error pops up again, I think something has changed in Qt by design that causes this crash and this is some kind of backwards incompatibility issue instead of a bug.

I'm running on Os X El Capitan, and this error occurs with

~~~
OpenSesame 3.1.3
Qt 5.7.0 
PyQt 5.7 
QScintilla 2.9.3
QProgEdit 4.0.6
~~~

**Comment by dschreij** [comment]
I have to add, that this error only occurs with the combination of PyQt5 and Python 2, not with Python 3.
Since we are planning on making the switch sooner or later anyway, I wouldn't pay much attention to it. If you think this switch will be a while (and we still want to push the Mac version of OpenSesame to Qt5 ASAP) it might be worthwhile to find a temporary solution to this problem (even though it might be a hacky one...)

**Comment by dschreij** [comment]
Another thing is that anaconda (from which as you know we build the mac package) has just released Qt5 on their official channel, but still use version 5.6, with which this problem doesn't occur. So another reason to give this a low priority for now...

**Comment by smathot** [comment]
I'll take a look at it; it seems that Ubuntu 16.10 comes with PyQt 5.7, so maybe I can reproduce the issue there. It's probably easily fixed.

**Comment by dschreij** [comment]
This was solved for me by compiling Qt5 from source, and not use the 'bottled' version provided by Homebrew. I think this can be closed, but I'm not 100% certain.

**Comment by smathot** [comment]
So you're talking about compiling Qt 5.7 from source, right? And that works? In that case, I suggest we close the issue. If it resurfaces in an environment that is directly relevant to users (I suspect you may be the only one to have ever run into it), we can take a closer look at it. Agreed?

**Comment by dschreij** [comment]
Yes, sounds like the right approach.
